type Product = {
  id: string;          // Generated by the database
  name: string;
  description: string;
  price: number;
  stock: number;
  category: 'electronics' | 'books' | 'apparel';
  createdAt: Date;     // Set by the server on creation
  updatedAt: Date;     // Set by the server on update
};

const products: Product[] = [
    {
        id: 'abc-123',
        name: 'Quantum Laptop',
        description: 'A laptop from the future.',
        price: 2500,
        stock: 15,
        category: 'electronics',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'def-456',
        name: 'Ergonomic Keyboard',
        description: 'Type for hours without strain.',
        price: 150,
        stock: 50,
        category: 'electronics',
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

type updateProductSuccessResponse={
    status:true;
    product:Product;
}

type updateProductFailureResponse={
    status:false;
    message:string;
}

export type UpdateProductResponse=updateProductFailureResponse | updateProductSuccessResponse;

export async function updateProduct(id:string,data:Partial<Product>):Promise<UpdateProductResponse>{
  return new Promise((resolve,reject)=>{
    setTimeout(()=>{
      try{
        const result=products.find(product=>product.id===id);
        if(result!=undefined){
          Object.assign(result,data);
          result.updatedAt=new Date();
          resolve({status:true,product:result})
        }else{
          resolve({status:false,message:'Product not found'})
        }
      }catch(error){
        reject(new Error(`Error updating product ${error}`))
      }
    },1000)
  })
}

export type Review = {
  userId: string;
  rating: 1 | 2 | 3 | 4 | 5;
  comment: string;
};

export async function getProductDetails(id: string): Promise<Product | undefined> {
  console.log(`Fetching details for product ${id}...`);
  return new Promise((resolve) => {
    setTimeout(() => {
      const product = products.find(p => p.id === id);
      console.log(`Found details for ${id}.`);
      resolve(product);
    }, 500);
  });
}

export async function getProductStock(id: string): Promise<number> {
  console.log(`Fetching stock for product ${id}...`);
  return new Promise((resolve) => {
    setTimeout(() => {
      // In a real system, this would be a database query.
      const stock = 42; 
      console.log(`Stock for ${id} is ${stock}.`);
      resolve(stock);
    }, 200);
  });
}

export async function getProductReviews(id: string): Promise<Review[]> {
  console.log(`Fetching reviews for product ${id}...`);
  return new Promise((resolve) => {
    setTimeout(() => {
      // In a real system, this would be another database query.
      const reviews: Review[] = [
        { userId: 'user-1', rating: 5, comment: 'Absolutely fantastic!' },
        { userId: 'user-2', rating: 4, comment: 'Works well, but a bit pricey.' },
      ];
      console.log(`Found ${reviews.length} reviews for ${id}.`);
      resolve(reviews);
    }, 800);
  });
}

function logProductAnalytics(data:Readonly<Product>):void{}