type UnpackArray<T> = T extends (infer R)[] ? R : T;

type Product = {
  id: string;          // Generated by the database
  name: string;
  description: string;
  price: number;
  stock: number;
  category: 'electronics' | 'books' | 'apparel';
  createdAt: Date;     // Set by the server on creation
  updatedAt: Date;     // Set by the server on update
};

// --- Test Types for `infer` ---

// Test the "true" path: Unpacking an array of objects
type UnpackedProducts = UnpackArray<Product[]>; // Hover over this: it should resolve to `Product`

// Test the "false" path: Passing a non-array type
type UnpackedString = UnpackArray<string>; // Hover over this: it should resolve to `string`