// Our canonical Product model, representing what's in the database.
type Product = {
  id: string;          // Generated by the database
  name: string;
  description: string;
  price: number;
  stock: number;
  category: 'electronics' | 'books' | 'apparel';
  createdAt: Date;     // Set by the server on creation
  updatedAt: Date;     // Set by the server on update
};
